Add default libs

diff --git a/fix-python b/fix-python
--- a/fix-python
+++ b/fix-python
@@ -3,11 +3,22 @@ set -e
 
 # This script fix issues with Python binaries on NixOS
 # Usage:
-# fix-python --venv .venv --libs libs.nix
+# fix-python --venv .venv [--libs libs.nix]
+
+DEFAULT_LIBS_EXPRESSION="
+(
+  let pkgs = import (builtins.getFlake \"nixpkgs\") { };
+  in [
+    pkgs.gcc.cc
+    pkgs.glibc
+    pkgs.zlib
+  ]
+)
+"
 
 # Help
 if [ "$1" = "--help" ]; then
-  echo "Usage: fix-python --venv .venv --libs libs.nix"
+  echo "Usage: fix-python --venv .venv [--libs libs.nix]"
   echo "--venv: path to Python virtual environment"
   echo "--libs: path to a Nix file which returns a list of derivations"
   echo "--gpu: enable GPU support"
@@ -34,7 +45,7 @@ while [ $# -gt 0 ]; do
       ;;
     *)
       echo "Unknown argument: $1"
-      echo "Usage: fix-python --venv .venv --libs libs.nix"
+      echo "Usage: fix-python --venv .venv [--libs libs.nix]"
       exit 1
       ;;
   esac
@@ -44,14 +55,8 @@ done
 # check arguments
 if [ -z "$VENV_PATH" ]; then
   echo "Missing argument: --venv"
-  echo "Usage: fix-python --venv .venv --libs libs.nix"
+  echo "Usage: fix-python --venv .venv [--libs libs.nix]"
   echo "or set VENV_PATH"
-  exit 1
-fi
-if [ -z "$LIBS_PATH" ]; then
-  echo "Missing argument: --libs"
-  echo "Usage: fix-python --venv .venv --libs libs.nix"
-  echo "or set LIBS_PATH"
   exit 1
 fi
 
@@ -72,16 +77,27 @@ then
 fi
 
 # load libs from Nix file
-mkdir -p .nix/fix-python
-nix_libs_build_status=$(nix build --impure --expr "import $LIBS_PATH" -o .nix/fix-python/result; echo $?)
-if [ "$nix_libs_build_status" -eq "1" ]; then
-  echo "Failed to load libs from Nix file $LIBS_PATH"
-  echo ""
-  echo "Try to debug this issue with the command:"
-  echo "    nix build --impure --expr \"import $LIBS_PATH\""
-  exit 1
+if [ "$LIBS_PATH" ];
+then
+  custom_libs_expression="(import $LIBS_PATH)"
+  mkdir -p .nix/fix-python
+  nix_libs_build_status=$(
+    nix build --impure --expr "$custom_libs_expression" -o .nix/fix-python/result
+    echo $?
+  )
+  if [ "$nix_libs_build_status" -eq "1" ];
+  then
+    echo "Failed to load libs from Nix file $LIBS_PATH"
+    echo ""
+    echo "Try to debug this issue with the command:"
+    echo "    nix build --impure --expr \"import $LIBS_PATH\""
+    exit 1
+  fi
+else
+  custom_libs_expression="[]"
 fi
-nixos_python_nix_libs="$(nix eval --impure --expr "let pkgs = import (builtins.getFlake \"nixpkgs\") {}; in pkgs.lib.strings.makeLibraryPath (import $LIBS_PATH)" | sed 's/^"\(.*\)"$/\1/')"
+all_nix_libs_expression="($custom_libs_expression ++ $DEFAULT_LIBS_EXPRESSION)"
+nixos_python_nix_libs="$(nix eval --impure --expr "let pkgs = import (builtins.getFlake \"nixpkgs\") {}; in pkgs.lib.strings.makeLibraryPath $all_nix_libs_expression" | sed 's/^"\(.*\)"$/\1/')"
 if [ "$verbose" ]; then echo "nixos_python_nix_libs=$nixos_python_nix_libs"; fi
 libs="$nixos_python_nix_libs"
 
